# Generated by Django 4.2.11 on 2026-03-11 12:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RSVP', '0002_alter_rsvp_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rsvp',
            unique_together={('user', 'event')},
        ),
    ]
